/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedEspaceRouteImport } from './routes/_authenticated/espace'
import { Route as AuthenticatedFamilleRouteImport } from './routes/_authenticated/famille'
import { Route as AuthenticatedMaitreRouteImport } from './routes/_authenticated/maitre'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAffectationsRouteImport } from './routes/_authenticated/admin/affectations'
import { Route as AuthenticatedAdminFamillesRouteImport } from './routes/_authenticated/admin/familles'
import { Route as AuthenticatedAdminMaitresRouteImport } from './routes/_authenticated/admin/maitres'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEspaceRoute = AuthenticatedEspaceRouteImport.update({
  id: '/espace',
  path: '/espace',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFamilleRoute = AuthenticatedFamilleRouteImport.update({
  id: '/famille',
  path: '/famille',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaitreRoute = AuthenticatedMaitreRouteImport.update({
  id: '/maitre',
  path: '/maitre',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAffectationsRoute =
  AuthenticatedAdminAffectationsRouteImport.update({
    id: '/admin/affectations',
    path: '/admin/affectations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminFamillesRoute =
  AuthenticatedAdminFamillesRouteImport.update({
    id: '/admin/familles',
    path: '/admin/familles',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMaitresRoute =
  AuthenticatedAdminMaitresRouteImport.update({
    id: '/admin/maitres',
    path: '/admin/maitres',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/espace': typeof AuthenticatedEspaceRoute
  '/famille': typeof AuthenticatedFamilleRoute
  '/maitre': typeof AuthenticatedMaitreRoute
  '/admin/affectations': typeof AuthenticatedAdminAffectationsRoute
  '/admin/familles': typeof AuthenticatedAdminFamillesRoute
  '/admin/maitres': typeof AuthenticatedAdminMaitresRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/espace': typeof AuthenticatedEspaceRoute
  '/famille': typeof AuthenticatedFamilleRoute
  '/maitre': typeof AuthenticatedMaitreRoute
  '/admin/affectations': typeof AuthenticatedAdminAffectationsRoute
  '/admin/familles': typeof AuthenticatedAdminFamillesRoute
  '/admin/maitres': typeof AuthenticatedAdminMaitresRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/espace': typeof AuthenticatedEspaceRoute
  '/_authenticated/famille': typeof AuthenticatedFamilleRoute
  '/_authenticated/maitre': typeof AuthenticatedMaitreRoute
  '/_authenticated/admin/affectations': typeof AuthenticatedAdminAffectationsRoute
  '/_authenticated/admin/familles': typeof AuthenticatedAdminFamillesRoute
  '/_authenticated/admin/maitres': typeof AuthenticatedAdminMaitresRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/espace'
    | '/famille'
    | '/maitre'
    | '/admin/affectations'
    | '/admin/familles'
    | '/admin/maitres'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/espace'
    | '/famille'
    | '/maitre'
    | '/admin/affectations'
    | '/admin/familles'
    | '/admin/maitres'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/espace'
    | '/_authenticated/famille'
    | '/_authenticated/maitre'
    | '/_authenticated/admin/affectations'
    | '/_authenticated/admin/familles'
    | '/_authenticated/admin/maitres'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/espace': {
      id: '/_authenticated/espace'
      path: '/espace'
      fullPath: '/espace'
      preLoaderRoute: typeof AuthenticatedEspaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/famille': {
      id: '/_authenticated/famille'
      path: '/famille'
      fullPath: '/famille'
      preLoaderRoute: typeof AuthenticatedFamilleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maitre': {
      id: '/_authenticated/maitre'
      path: '/maitre'
      fullPath: '/maitre'
      preLoaderRoute: typeof AuthenticatedMaitreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/affectations': {
      id: '/_authenticated/admin/affectations'
      path: '/admin/affectations'
      fullPath: '/admin/affectations'
      preLoaderRoute: typeof AuthenticatedAdminAffectationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/familles': {
      id: '/_authenticated/admin/familles'
      path: '/admin/familles'
      fullPath: '/admin/familles'
      preLoaderRoute: typeof AuthenticatedAdminFamillesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/maitres': {
      id: '/_authenticated/admin/maitres'
      path: '/admin/maitres'
      fullPath: '/admin/maitres'
      preLoaderRoute: typeof AuthenticatedAdminMaitresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedEspaceRoute: typeof AuthenticatedEspaceRoute
  AuthenticatedFamilleRoute: typeof AuthenticatedFamilleRoute
  AuthenticatedMaitreRoute: typeof AuthenticatedMaitreRoute
  AuthenticatedAdminAffectationsRoute: typeof AuthenticatedAdminAffectationsRoute
  AuthenticatedAdminFamillesRoute: typeof AuthenticatedAdminFamillesRoute
  AuthenticatedAdminMaitresRoute: typeof AuthenticatedAdminMaitresRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedEspaceRoute: AuthenticatedEspaceRoute,
  AuthenticatedFamilleRoute: AuthenticatedFamilleRoute,
  AuthenticatedMaitreRoute: AuthenticatedMaitreRoute,
  AuthenticatedAdminAffectationsRoute: AuthenticatedAdminAffectationsRoute,
  AuthenticatedAdminFamillesRoute: AuthenticatedAdminFamillesRoute,
  AuthenticatedAdminMaitresRoute: AuthenticatedAdminMaitresRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
